//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoDownloader.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VideoDownloader.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        internal static string ConvertButton_Tooltiptext {
            get {
                return ResourceManager.GetString("ConvertButton_Tooltiptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The video url must be specified..
        /// </summary>
        internal static string ErrEmptyUrlBox {
            get {
                return ResourceManager.GetString("ErrEmptyUrlBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error during the querying of the formats..
        /// </summary>
        internal static string ErrFormatQuerying {
            get {
                return ResourceManager.GetString("ErrFormatQuerying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string ErrGeneralTitle {
            get {
                return ResourceManager.GetString("ErrGeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http error: Retrying;Invalid URL!;Unsupported URL!;This video is unavailable.;Unable to download webpage.;Unknown URL type;Connection refused.;Youtube said: This channel does not exist.;The video not found.;XML error! Could not find XML element.;XML error! Unable to download XML.;Unable to download XML (Forbidden 403);Unable to download video data.;Output format error.;Unable to open for writing.;Incomplete YouTube ID.;The ffmpeg not found, the file could not converted.;Signature extraction failed.;Unable t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ErrorStrings {
            get {
                return ResourceManager.GetString("ErrorStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when starting program. A necessary file could not be loaded:.
        /// </summary>
        internal static string ErrProgramStartMsg {
            get {
                return ResourceManager.GetString("ErrProgramStartMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string ErrUnknown {
            get {
                return ResourceManager.GetString("ErrUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The youtube-dl program could not be updated, the file is in use..
        /// </summary>
        internal static string ErrUpdateProgramInUse {
            get {
                return ResourceManager.GetString("ErrUpdateProgramInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string InfoGeneralTitle {
            get {
                return ResourceManager.GetString("InfoGeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update was successful..
        /// </summary>
        internal static string InfoUpdateSuccess {
            get {
                return ResourceManager.GetString("InfoUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing processes, please wait....
        /// </summary>
        internal static string MainWindowsClosing {
            get {
                return ResourceManager.GetString("MainWindowsClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected videos.
        /// </summary>
        internal static string PlayListName {
            get {
                return ResourceManager.GetString("PlayListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding.
        /// </summary>
        internal static string ProgressBoxAdding {
            get {
                return ResourceManager.GetString("ProgressBoxAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        internal static string Status_Aborted {
            get {
                return ResourceManager.GetString("Status_Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborting....
        /// </summary>
        internal static string Status_Aborting {
            get {
                return ResourceManager.GetString("Status_Aborting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding thumbnail....
        /// </summary>
        internal static string Status_AddPicture {
            get {
                return ResourceManager.GetString("Status_AddPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already downloaded.
        /// </summary>
        internal static string Status_Already {
            get {
                return ResourceManager.GetString("Status_Already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting (FFmpeg)....
        /// </summary>
        internal static string Status_Converting {
            get {
                return ResourceManager.GetString("Status_Converting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting original....
        /// </summary>
        internal static string Status_DelOriginal {
            get {
                return ResourceManager.GetString("Status_DelOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        internal static string Status_Error {
            get {
                return ResourceManager.GetString("Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Status_Finished {
            get {
                return ResourceManager.GetString("Status_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending....
        /// </summary>
        internal static string Status_Pending {
            get {
                return ResourceManager.GetString("Status_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress:.
        /// </summary>
        internal static string Status_Progress0 {
            get {
                return ResourceManager.GetString("Status_Progress0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed:.
        /// </summary>
        internal static string Status_Progress1 {
            get {
                return ResourceManager.GetString("Status_Progress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETA:.
        /// </summary>
        internal static string Status_Progress2 {
            get {
                return ResourceManager.GetString("Status_Progress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resuming at  byte.
        /// </summary>
        internal static string Status_Resume0 {
            get {
                return ResourceManager.GetString("Status_Resume0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Status_Resume1 {
            get {
                return ResourceManager.GetString("Status_Resume1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        internal static string Status_Starting {
            get {
                return ResourceManager.GetString("Status_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update youtube-dl!.
        /// </summary>
        internal static string UpdateButtonTextNormal {
            get {
                return ResourceManager.GetString("UpdateButtonTextNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        internal static string UpdateButtonTextUpdating {
            get {
                return ResourceManager.GetString("UpdateButtonTextUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string WarnGeneralTitle {
            get {
                return ResourceManager.GetString("WarnGeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language was changed. The program needs to  restarting to take effect of change..
        /// </summary>
        internal static string WarnLanguageChanged {
            get {
                return ResourceManager.GetString("WarnLanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to reset the program to its default settings?.
        /// </summary>
        internal static string WarnRestoreSettings {
            get {
                return ResourceManager.GetString("WarnRestoreSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This URL has already added..
        /// </summary>
        internal static string WarnUrlAlreadyAdded {
            get {
                return ResourceManager.GetString("WarnUrlAlreadyAdded", resourceCulture);
            }
        }
    }
}
